language: rust
sudo: false

cache: cargo

matrix:
  include:

  # Build WebAssembly with wasm-pack.
  - language: rust
    env: RUST_BACKTRACE=1
    addons:
      firefox: latest
      chrome: stable
    before_script:
      - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
      - (test -x $HOME/.cargo/bin/cargo-generate || cargo install --vers "^0.2" cargo-generate)
      - cargo install-update -a
      - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
    script:
      - cargo generate --git . --name testing
      # Having a broken Cargo.toml (in that it has curlies in fields) anywhere
      # in any of our parent dirs is problematic.
      - mv Cargo.toml Cargo.toml.tmpl
      - cd testing
      - wasm-pack build
      - wasm-pack test --chrome --firefox --headless

  # Build JavaScript with webpack.
  - language: node_js
    node_js: 10
    script:
    - npm run build

deploy:
  provider: pages
  local_dir: testing/dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master